ALTER TABLE "Score" ADD COLUMN "perfects" INTEGER;
ALTER TABLE "Score" ADD COLUMN "greats" INTEGER;
ALTER TABLE "Score" ADD COLUMN "good" INTEGER;
ALTER TABLE "Score" ADD COLUMN "bad" INTEGER;
ALTER TABLE "Score" ADD COLUMN "misses" INTEGER;
ALTER TABLE "Score" ADD COLUMN "combo" INTEGER;
ALTER TABLE "Score" ADD COLUMN "total" INTEGER;
