const songBadges = {
  drill: [
    { level: 1, song: 'Vook', songId: 340, mode: 'item_single', diff: 'lv_15' },
    { level: 2, song: 'Solitary 1.5', songId: 457, mode: 'item_single', diff: 'lv_16' },
    { level: 3, song: 'Gun Rock', songId: 433, mode: 'item_single', diff: 'lv_17' },
    { level: 4, song: 'Moonlight', songId: 233, mode: 'item_single', diff: 'lv_18' },
    { level: 5, song: 'Vacuum', songId: 164, mode: 'item_single', diff: 'lv_19' },
    { level: 6, song: 'Overblow', songId: 259, mode: 'item_single', diff: 'lv_20' },
    { level: 7, song: 'Sorceress Elise', songId: 60, mode: 'item_single', diff: 'lv_21' },
    { level: 8, song: 'Rock the house', songId: 78, mode: 'item_double', diff: 'lv_22' },
    { level: 9, song: 'Witch Doctor', songId: 294, mode: 'item_double', diff: 'lv_23' },
    { level: 10, song: 'Wi-Ex-Doc-Va', songId: 410, mode: 'item_double', diff: 'lv_24' },
    { level: 'Expert', song: 'All 10 Titles', songId: 1 },
  ],
  gimmick: [
    { level: 1, song: 'Yeo rae a', songId: 147, mode: 'item_single', diff: 'lv_13' },
    { level: 2, song: 'Bad Apple', songId: 6, mode: 'item_single', diff: 'lv_15' },
    { level: 3, song: 'Love Scenario', songId: 7, mode: 'item_single', diff: 'lv_17' },
    { level: 4, song: 'Come to Me', songId: 351, mode: 'item_single', diff: 'lv_17' },
    { level: 5, song: 'Rock the house - SHORT CUT -', songId: 313, mode: 'item_single', diff: 'lv_18' },
    { level: 6, song: "Miss S' Story", songId: 449, mode: 'item_single', diff: 'lv_19' },
    { level: 7, song: 'Nakakapagpabagabag', songId: 84, mode: 'item_single', diff: 'lv_19' },
    { level: 8, song: 'Twist of Fate', songId: 182, mode: 'item_single', diff: 'lv_19' },
    { level: 9, song: 'Everybody Got 2 Know', songId: 480, mode: 'item_single', diff: 'lv_19' },
    { level: 10, song: '8 6', songId: 26, mode: 'item_single', diff: 'lv_20' },
    { level: 'Expert', song: 'All 10 Titles', songId: 1 },
  ],
  half: [
    { level: 1, song: 'Trashy Innocence', songId: 125, mode: 'item_double', diff: 'lv_16' },
    { level: 2, song: 'Butterfly', songId: 240, mode: 'item_double', diff: 'lv_17' },
    { level: 3, song: 'Shub Niggurath', songId: 141, mode: 'item_double', diff: 'lv_18' },
    { level: 4, song: 'Super Fantasy', songId: 22, mode: 'item_double', diff: 'lv_18' },
    { level: 5, song: 'Phantom', songId: 312, mode: 'item_double', diff: 'lv_19' },
    { level: 6, song: 'Utsushiyo no Kaze', songId: 285, mode: 'item_double', diff: 'lv_20' },
    { level: 7, song: 'Witch Doctor #1', songId: 448, mode: 'item_double', diff: 'lv_21' },
    { level: 8, song: 'Bad Apple - FULL SONG -', songId: 134, mode: 'item_double', diff: 'lv_22' },
    { level: 9, song: 'Love is a Danger Zone 2 Try to B.P.M.', songId: 496, mode: 'item_double', diff: 'lv_23' },
    { level: 10, song: 'Imprinting', songId: 85, mode: 'item_double', diff: 'lv_24' },
    { level: 'Expert', song: 'All 10 Titles', songId: 1 },
  ],
  run: [
    { level: 1, song: 'Final Audition', songId: 225, mode: 'item_double', diff: 'lv_15' },
    { level: 2, song: 'Super Fantasy', songId: 22, mode: 'item_single', diff: 'lv_16' },
    { level: 3, song: 'Pavane', songId: 382, mode: 'item_single', diff: 'lv_17' },
    { level: 4, song: 'Gothique Resonance', songId: 272, mode: 'item_single', diff: 'lv_18' },
    { level: 5, song: 'Napalm', songId: 274, mode: 'item_single', diff: 'lv_19' },
    { level: 6, song: 'Bee', songId: 310, mode: 'item_double', diff: 'lv_20' },
    { level: 7, song: 'Sarabande', songId: 90, mode: 'item_double', diff: 'lv_21' },
    { level: 8, song: 'Just Hold On (To All Fighters)', songId: 140, mode: 'item_double', diff: 'lv_22' },
    { level: 9, song: 'Final Audition Ep. 2-X', songId: 462, mode: 'item_single', diff: 'lv_23', grade: 'S' },
    { level: 10, song: 'Yog Sothoth', songId: 127, mode: 'item_double', diff: 'lv_24' },
    { level: 'Expert', song: 'All 10 Titles', songId: 1 },
  ],
  twist: [
    { level: 1, song: 'Street Showdown', songId: 413, mode: 'item_single', diff: 'lv_15' },
    { level: 2, song: 'Final Audition 3', songId: 342, mode: 'item_single', diff: 'lv_16' },
    { level: 3, song: 'U Got Me Rocking', songId: 246, mode: 'item_single', diff: 'lv_17' },
    { level: 4, song: 'Final Audition', songId: 225, mode: 'item_double', diff: 'lv_18' },
    { level: 5, song: 'Super Fantasy', songId: 22, mode: 'item_single', diff: 'lv_19' },
    { level: 6, song: 'Witch Doctor #1', songId: 448, mode: 'item_double', diff: 'lv_20' },
    { level: 7, song: 'LIADZ', songId: 273, mode: 'item_double', diff: 'lv_21' },
    { level: 8, song: 'LIADZ pt 2', songId: 318, mode: 'item_single', diff: 'lv_22' },
    { level: 9, song: 'LIADZ (Cranky)', songId: 161, mode: 'item_double', diff: 'lv_23' },
    { level: 10, song: 'Bee', songId: 310, mode: 'item_double', diff: 'lv_24' },
    { level: 'Expert', song: 'All 10 Titles', songId: 1 },
  ],
};

const metaBadges = {
  twist: '[Twist] Expert',
  specialist: 'Specialist',
};

module.exports = { songBadges, metaBadges };
