language: node_js
node_js:
  - '12'
services:
  - postgres
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/trackitup
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
