version: '3'

services:

  node-app:
    build: .
    image: node-app
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/trackitup
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: trackitup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  pgdata:

networks:
  node-network:
    driver: bridge
